version: '3.4'
services: 
  redis-cluster:
    build: 
      context: redis
      dockerfile: Dockerfile
    container_name: redis-cluster
    volumes:
     - /home/docker/compose/redis/data:/redis/cluster/work_spac
    network_mode: host
    command: "/redis/cluster/build.sh"
