version: '3.4'
services:
  nginx: 
    image: docker.io/nginx:1.14.1
    container_name: nginx
    restart: always
    volumes:
      - /home/docker/compose/nginx/logs:/var/log/nginx
      - /home/docker/compose/nginx/conf:/etc/nginx
      - /home/docker/compose/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment: 
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
     memlock:
       soft: -1
       hard: -1
    volumes:
      - /home/docker/compose/elasticsearch/data:/usr/shar/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/compose/elasticsearch/es1.yml:/user/share/elasticsearch/conf/elasticsearch.yml:ro
    ports:
      - 9200:9200
  mysql:
    image: docker.io/mysql:5.7.21
    restart: always
    container_name: mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/compose/mysql/data:/var/lib/mysql
      - /home/docker/compose/mysql/conf:/etc/mysql
    ports:
      - 33006:3306
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 'yourpassword'
  redis-cluster:
    build:
      context: redis
      dockerfile: Dockerfile
    container_name: redis-cluster
    volumes:
     - /home/docker/compose/redis/data:/redis/cluster/work_spac
    command: "/redis/cluster/build.sh"
