version: '3.4'
services:
  nginx: 
    image: docker.io/nginx:1.14.1
    container_name: nginx
    restart: always
    volumes:
      - /home/docker/compose/nginx/logs:/var/log/nginx
      - /home/docker/compose/nginx/conf:/etc/nginx
      - /home/docker/compose/nginx/html:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment: 
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
     memlock:
       soft: -1
       hard: -1
    volumes:
      - /home/docker/compose/elasticsearch/data:/usr/shar/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/compose/elasticsearch/es1.yml:/user/share/elasticsearch/conf/elasticsearch.yml:ro
    ports:
      - 9200:9200
  mysql:
    image: docker.io/mysql:5.7.21
    restart: always
    container_name: mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/compose/mysql/data:/var/lib/mysql
      - /home/docker/compose/mysql/conf:/etc/mysql
    ports:
      - 33006:3306
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: 'yourpassword'
  gogs:
    image: gogs/gogs
    restart: always
    container_name: gogs
    depends_on: 
      - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/compose/gogs/data:/data
    ports: 
      - "3000:3000"
      - "3022:22"
  redis-cluster:
    build:
      context: redis
      dockerfile: Dockerfile
    container_name: redis-cluster
    volumes:
     - /home/docker/compose/redis/data:/redis/cluster/work_spac
    command: "/redis/cluster/build.sh"
  mongodb:
     build:
       context: mongo
       dockerfile: Dockerfile
     container_name: mongodb
     restart: always
     volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/compose/mongo/work_spac:/home/mongodb/work_spac
     ports:
      - "27000:27000"
      - "27001:27001"
      - "27002:27002"
     command: "/home/mongodb/startup.sh"
  zoo1:
   image: registry.cn-hangzhou.aliyuncs.com/gy-team/zookeeper:3.4.13
   restart: always
   hostname: zoo1
   container_name: zoo1
   volumes:
    - /home/docker/compose/zookeeper/zoo1/data:/data
    - /home/docker/compose/zookeeper/zoo1/datalog:/datalog
    - /home/docker/compose/zookeeper/zoo1/conf:/conf
   ports:
     - 2181:2181
   environment:
     ZOO_MY_ID: 1
     ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo2:
   image: registry.cn-hangzhou.aliyuncs.com/gy-team/zookeeper:3.4.13
   restart: always
   hostname: zoo2
   container_name: zoo2
   volumes:
    - /home/docker/compose/zookeeper/zoo2/data:/data
    - /home/docker/compose/zookeeper/zoo2/datalog:/datalog
    - /home/docker/compose/zookeeper/zoo2/conf:/conf
   ports:
     - 2182:2181
   environment:
     ZOO_MY_ID: 2
     ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
  zoo3:
   image: registry.cn-hangzhou.aliyuncs.com/gy-team/zookeeper:3.4.13
   restart: always
   hostname: zoo3
   container_name: zoo3
   volumes:
    - /home/docker/compose/zookeeper/zoo3/data:/data
    - /home/docker/compose/zookeeper/zoo3/datalog:/datalog
    - /home/docker/compose/zookeeper/zoo3/conf:/conf
   ports:
     - 2183:2181
   environment:
     ZOO_MY_ID: 3
     ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
